#! /usr/bin/perl
use strict;
use warnings;
# SOLVED
#
=ignore

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

print 285*(285 + 1) / 2,"\n"; # equals 40755

=cut
my $tri_total;
my $hex_total;
my $pent_total;
my @similar_totals;

for my $pent ( 2..100000 ) { ## 1533776805
        $pent_total = $pent*( 3 * $pent - 1 ) / 2;
    for my $hex ( 2..100000 ) {
        $hex_total  = $hex*( 2 * $hex - 1);
       if ( $hex_total == $pent_total ) {
            push @similar_totals, $hex_total;
            print "found: ". $hex_total,"\n";
        }

    }

}

